<?php

namespace Database\Seeders\Media;

use App\Models\Media;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MediaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public $media = array(
        array('id' => '1','title' => 'Dark','slug' => 'dark','synopsis' => 'Una saga familiar con un toque sobrenatural, ambientada en una ciudad alemana donde la desaparición de dos niños pequeños expone las relaciones entre cuatro familias.','release_date' => '2017-01-01','number_collection' => NULL,'duration' => NULL,'rating' => '5','personal_description' => NULL,'media_type' => '2','start_date' => '2018-01-01','end_date' => '2020-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLnBULuU933LDSL160Ep4cX9ze1QFlW7P27g&s','uuid' => 'OK3ftpvN3dMo2bzLahjg4Vxb','status' => '2','user_id' => '1','created_at' => '2025-02-24 16:17:23','updated_at' => '2025-02-24 16:20:55'),
        array('id' => '2','title' => 'Los Juegos del Hambre','slug' => 'los-juegos-del-hambre','synopsis' => 'Katniss Everdeen toma voluntariamente el lugar de su hermana pequeña en los Juegos del Hambre, un concurso de televisión en la que dos adolescentes elegidos al azar de cada uno de los doce distritos de Panem luchan hasta la muerte.','release_date' => '2012-01-01','number_collection' => '1','duration' => '142','rating' => '4','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://m.media-amazon.com/images/S/pv-target-images/93249319ce1fab3e75ea0b82fea6e3e256c663fcad4aa4465ad5d374535bbc39.jpg','uuid' => 'bOwl69aeHYoPFdvYC7nL8foC','status' => '2','user_id' => '1','created_at' => '2025-02-25 13:14:20','updated_at' => '2025-02-25 13:59:00'),
        array('id' => '3','title' => 'Los Juegos del Hambre: En llamas','slug' => 'los-juegos-del-hambre-en-llamas','synopsis' => 'Katniss Everdeen y Peeta Mellark se convierten en objetivo del Capitolio después de que su victoria en los 74º Juegos del Hambre desencadene una rebelión en los distritos de Panem.','release_date' => '2013-01-01','number_collection' => '2','duration' => '146','rating' => '4','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img2.acsta.net/pictures/210/455/21045552_20131001101323189.jpg','uuid' => 'Z6GYtqQ2qfIq2k8jkC21C4lE','status' => '2','user_id' => '1','created_at' => '2025-02-25 13:18:38','updated_at' => '2025-02-25 13:59:14'),
        array('id' => '4','title' => 'Los Juegos del Hambre: Sinsajo Parte 1','slug' => 'los-juegos-del-hambre-sinsajo-parte-1','synopsis' => 'Katniss Everdeen se encuentra en el distrito 13 tras destrozar los juegos para siempre. Bajo el liderazgo de la presidenta Coin y el consejo de sus amigos, Katniss despliega sus alas mientras lucha por salvar a Peeta y a la nación.','release_date' => '2014-01-01','number_collection' => '3','duration' => '123','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => NULL,'cover_image' => NULL,'cover_image_url' => 'https://es.web.img3.acsta.net/pictures/14/09/12/10/51/011753.jpg','uuid' => 'Q6LGepBYhUKd08K6GVjsYgJy','status' => '1','user_id' => '1','created_at' => '2025-02-25 13:20:50','updated_at' => '2025-02-25 13:59:22'),
        array('id' => '5','title' => 'Los Juegos del Hambre: Sinsajo Parte 2','slug' => 'los-juegos-del-hambre-sinsajo-parte-2','synopsis' => 'Katniss y un equipo de rebeldes del distrito 13 se preparan para la batalla final que decidirá el futuro de Panem.','release_date' => '2015-01-01','number_collection' => '4','duration' => '137','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img2.acsta.net/pictures/15/10/05/09/45/058912.jpg','uuid' => 'O36tDXwGkcHBSP6aJQnwP0MH','status' => '2','user_id' => '1','created_at' => '2025-02-25 13:22:20','updated_at' => '2025-02-25 13:59:29'),
        array('id' => '6','title' => 'Shrek','slug' => 'shrek','synopsis' => 'Un malvado señor exilia a las criaturas de los cuentos de hadas al pantano de un ogro gruñón, que debe emprender una búsqueda y rescatar a una princesa para el señor con el fin de recuperar sus tierras.','release_date' => '2021-01-01','number_collection' => '1','duration' => '90','rating' => '4','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbucbkcasvOtVZT9YvrjaFhEiYHpTukHZJsA&s','uuid' => 'nZD6W27InzOgtRTT4pbyMXOa','status' => '2','user_id' => '1','created_at' => '2025-02-25 13:28:22','updated_at' => '2025-02-25 13:28:22'),
        array('id' => '7','title' => 'Shrek 2','slug' => 'shrek-2','synopsis' => 'Shrek y Fiona viajan al reino de Muy Muy Lejano, donde los padres de Fiona son reyes, para celebrar su matrimonio. Cuando llegan, descubren que no son tan bienvenidos como pensaban.','release_date' => '2004-01-01','number_collection' => '2','duration' => '93','rating' => '5','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img2.acsta.net/medias/nmedia/18/97/04/22/20504502.jpg','uuid' => 'BgL2WTigXdWLgRGBUB461grv','status' => '2','user_id' => '1','created_at' => '2025-02-25 13:31:39','updated_at' => '2025-02-25 13:31:39'),
        array('id' => '8','title' => 'Shrek Tercero','slug' => 'shrek-tercero','synopsis' => 'Designado a regañadientes como heredero de la tierra de Muy Muy Lejano, Shrek urde un plan para instalar al rebelde Artie como nuevo rey, mientras la princesa Fiona intenta evitar un golpe de estado del despechado Príncipe Encantador.','release_date' => '2007-01-01','number_collection' => '3','duration' => '93','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img3.acsta.net/medias/nmedia/18/63/15/86/18676530.jpg','uuid' => 'vO32blthyGMS7O3J5qYqQAL9','status' => '2','user_id' => '1','created_at' => '2025-02-25 13:34:40','updated_at' => '2025-02-25 13:34:40'),
        array('id' => '9','title' => 'Shrek Felices por Siempre','slug' => 'shrek-felices-por-siempre','synopsis' => 'Rumpelstiltskin engaña a un Shrek agobiado por su crisis de mediana edad para que se borre a si mismo de la existencia y se lance en una oscura línea temporal alternativa donde Rumpel gobierna supremamente.','release_date' => '2010-01-01','number_collection' => '4','duration' => '93','rating' => '2','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQYAyGqPnMfJd3wxEi5E8-TEydW-6k-U3efQ&s','uuid' => 'VmxB5mqzfjlaYoJpEVuO7dk5','status' => '2','user_id' => '1','created_at' => '2025-02-25 13:41:53','updated_at' => '2025-02-25 13:59:47'),
        array('id' => '10','title' => 'La Era de Hielo','slug' => 'la-era-de-hielo','synopsis' => 'En la Edad de Hielo, un tigre dientes de sable, un perezoso y un mamut lanudo encuentran a un bebé humano perdido y tratan de devolverlo a su tribu.','release_date' => '2002-01-01','number_collection' => '1','duration' => '81','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => NULL,'cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5sIs-omahlsK1wYBf2VnwoOOfLgRMePRQMg&s','uuid' => 'CVZm6gRDeP90pw4aSXzxU4vx','status' => '1','user_id' => '1','created_at' => '2025-02-25 13:55:07','updated_at' => '2025-02-25 14:00:01'),
        array('id' => '11','title' => 'La Era de Hielo 2: El Deshielo','slug' => 'la-era-de-hielo-2-el-deshielo','synopsis' => 'Manny, Sid y Diego descubren que la era glacial está llegando a su fin y se unen a todos para viajar a tierras más altas. Durante el viaje, descubren que Manny no es el último mamut lanudo.','release_date' => '2006-01-01','number_collection' => '2','duration' => '91','rating' => '4','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://i.pinimg.com/1200x/73/d8/6f/73d86f617f58015b6205163410172df2.jpg','uuid' => '2glkyBZrC6f3iyjfjKtUBgYc','status' => '2','user_id' => '1','created_at' => '2025-02-25 13:58:03','updated_at' => '2025-02-25 14:00:07'),
        array('id' => '12','title' => 'La Era de Hielo 3: El Origen de los Dinosaurios','slug' => 'la-era-de-hielo-3-el-origen-de-los-dinosaurios','synopsis' => 'Cuando Sid intenta adoptar tres huevos de dinosaurio, su madre real le secuestra y le lleva a un mundo perdido bajo tierra. Los amigos de Sid intentarán rescatarle.','release_date' => '2009-01-01','number_collection' => '3','duration' => '94','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://i.pinimg.com/736x/ad/9e/19/ad9e1950783fb5901ea06dae1ea4405e.jpg','uuid' => 'xabOvpA1A4djGCvMnMyfMy4k','status' => '2','user_id' => '1','created_at' => '2025-02-25 14:02:27','updated_at' => '2025-02-25 14:02:50'),
        array('id' => '13','title' => 'La Era de Hielo 4: La Formacion de los Continentes','slug' => 'la-era-de-hielo-4-la-formacion-de-los-continentes','synopsis' => 'Manny, Diego y Sid se embarcan en otra aventura después de que su continente quede a la deriva. Utilizando un iceberg como barco, se encuentran con criaturas marinas y luchan contra piratas mientras exploran un nuevo mundo.','release_date' => '2012-01-01','number_collection' => '4','duration' => '88','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFx1beuMj903OhO7SxA9szEwmlJ4teGiFIvw&s','uuid' => 'g8k8tIpPcFkuKsbEWaIC5LLD','status' => '2','user_id' => '1','created_at' => '2025-02-25 14:10:07','updated_at' => '2025-02-25 14:10:07'),
        array('id' => '14','title' => 'La Era de Hielo 5: El Gran Cataclismo','slug' => 'la-era-de-hielo-5-el-gran-cataclismo','synopsis' => 'La Manada debe encontrar una manera de evitar que un asteroide golpee la Tierra con la ayuda de un viejo amigo.','release_date' => '2016-01-01','number_collection' => '5','duration' => '94','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjuPQbmJwkw05Zkw3wg3EjphvQE6VnDBvvXA&s','uuid' => 'r5Gk23AlzsMqANEv1Y3geZBu','status' => '2','user_id' => '1','created_at' => '2025-02-25 14:12:15','updated_at' => '2025-02-25 14:12:15'),
        array('id' => '15','title' => 'Madagascar','slug' => 'madagascar','synopsis' => 'Un grupo de animales que ha pasado toda su vida en un zoo de Nueva York acaba en la selva de Madagascar, y debe adaptarse a vivir en la naturaleza.','release_date' => '2005-01-01','number_collection' => '1','duration' => '86','rating' => '4','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img2.acsta.net/medias/nmedia/18/68/23/11/20027493.jpg','uuid' => '02ta0b6eGrZ7tdaanCY6ckQS','status' => '2','user_id' => '1','created_at' => '2025-02-25 15:13:15','updated_at' => '2025-02-25 15:16:16'),
        array('id' => '16','title' => 'Madagascar 2: Escape a Africa','slug' => 'madagascar-2-escape-a-africa','synopsis' => 'Los animales de Madagascar vuelven a Nueva York, pero se estrellan en una reserva natural africana donde se encuentran con otros de su propia especie, y Alex descubre su ascendencia como príncipe de una manda de leones.','release_date' => '2008-01-01','number_collection' => '2','duration' => '89','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRYgfWFni02QaPMojFGFXLHjQzNRaymcyqHA&s','uuid' => 'ZKbC4sPFULeKwnHyS6ObU01L','status' => '2','user_id' => '1','created_at' => '2025-02-25 15:15:41','updated_at' => '2025-02-25 15:15:41'),
        array('id' => '17','title' => 'Madagascar 3: De Marcha por Europa','slug' => 'madagascar-3-de-marcha-por-europa','synopsis' => 'Los animales de Madagascar se unen a un circo europeo en apuros para regresar a Nueva York, pero se ven perseguidos por un oficial psicótico de control de animales.','release_date' => '2012-01-01','number_collection' => '3','duration' => '95','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://pics.filmaffinity.com/Madagascar_3_De_marcha_por_Europa-628965153-large.jpg','uuid' => 'BG28dQh5FWTlXqe2RBVGn4Sh','status' => '2','user_id' => '1','created_at' => '2025-02-25 15:17:34','updated_at' => '2025-02-25 15:17:34'),
        array('id' => '18','title' => 'Kung Fu Panda','slug' => 'kung-fu-panda','synopsis' => 'El Guerrero Dragón tiene que enfrentarse al salvaje Tai Lung, el destino de China está en juego. El pánico cunde cuando el manto del Guerrero Dragón le es otorgado a un panda gordinflón novato en artes marciales.','release_date' => '2008-01-01','number_collection' => '1','duration' => '92','rating' => '4','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img3.acsta.net/pictures/16/03/04/13/44/418557.jpg','uuid' => '9KBtLazsLyxXuZt1Fn2buumw','status' => '2','user_id' => '1','created_at' => '2025-02-25 15:19:09','updated_at' => '2025-02-25 15:19:09'),
        array('id' => '19','title' => 'Kung Fu Panda 2','slug' => 'kung-fu-panda-2','synopsis' => 'Po y sus amigos luchan para evitar que un malvado pavo real conquiste China con una nueva arma mortal. Pero primero, el Guerrero Dragón debe hacer las paces con su pasado.','release_date' => '2011-01-01','number_collection' => '2','duration' => '90','rating' => '4','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPAgcLaxY0EyWQCOjGoLVc5_BFV1SPifhmfQ&s','uuid' => 'FdM7eWMLukRuyzznZqFQxMBZ','status' => '2','user_id' => '1','created_at' => '2025-02-25 17:26:58','updated_at' => '2025-02-25 17:26:58'),
        array('id' => '20','title' => 'Kung Fu Panda 3','slug' => 'kung-fu-panda-3','synopsis' => 'Po se enfrenta a dos amenazas de dimensiones épicas: una sobrenatural, y otra más cotidiana.','release_date' => '2016-01-01','number_collection' => '3','duration' => '95','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img2.acsta.net/pictures/15/12/21/11/50/261408.jpg','uuid' => '6tMokPWyZ8yFrLqxpk93qQbo','status' => '2','user_id' => '1','created_at' => '2025-02-27 09:25:47','updated_at' => '2025-02-27 09:25:47'),
        array('id' => '21','title' => 'Kung Fu Panda 4','slug' => 'kung-fu-panda-4','synopsis' => 'Sigue a Po en sus aventuras por la antigua China, donde su amor por el kung fu sólo es comparable a su insaciable apetito.','release_date' => '2024-01-01','number_collection' => '4','duration' => '94','rating' => '3','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwVFwb9dpA4xILqS3KUR22V42hO1BNTyTT-Q&s','uuid' => '89oH8nZT8hT0vG0PfWxQrkZL','status' => '2','user_id' => '1','created_at' => '2025-02-27 09:26:59','updated_at' => '2025-02-27 09:26:59'),
        array('id' => '22','title' => 'Los 100','slug' => 'los-100','synopsis' => 'Noventa y siete años después de que una guerra haya destruido la civilización, una nave espacial que alberga a los supervivientes envía a cien delincuentes juveniles de vuelta a la Tierra, con la esperanza de repoblar el planeta.','release_date' => '2014-01-01','number_collection' => NULL,'duration' => NULL,'rating' => '4','personal_description' => NULL,'media_type' => '2','start_date' => '2024-01-01','end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img3.acsta.net/pictures/14/02/16/23/53/181925.jpg?coixp=50&coiyp=39','uuid' => 'nRssFBFXfDAyIm7yqlAz3Uvw','status' => '2','user_id' => '1','created_at' => '2025-02-27 13:17:03','updated_at' => '2025-02-27 13:17:03'),
        array('id' => '23','title' => 'Envidiosa','slug' => 'envidiosa','synopsis' => 'Vicky le da un ultimátum a su novio de toda la vida: cásate con ella o se va. Cuando las cosas no salen según lo planeado, persigue su sueño de casarse con una nueva pareja, lo que la lleva a un inesperado viaje de autodescubrimiento.','release_date' => '2024-01-01','number_collection' => NULL,'duration' => NULL,'rating' => '4','personal_description' => '','media_type' => '2','start_date' => '2024-05-01','end_date' => '2025-02-24','cover_image' => NULL,'cover_image_url' => 'https://images.pagina12.com.ar/styles/width960/public/2024-09/876508-envidiosa-serie-de-tv-151414786-large.jpg?itok=rrihyv3B','uuid' => 'oOCs2ZEyQC3xrsRjYxgCpPin','status' => '2','user_id' => '1','created_at' => '2025-02-27 13:27:31','updated_at' => '2025-02-27 13:27:31'),
        array('id' => '24','title' => 'Vikingos','slug' => 'vikingos','synopsis' => 'El brutal y misterioso mundo de Ragnar Lothbrok, un guerrero y agricultor vikingo que anhela explorar y asaltar las costas distantes a lo largo del océano.','release_date' => '2013-01-01','number_collection' => NULL,'duration' => NULL,'rating' => '4','personal_description' => NULL,'media_type' => '2','start_date' => NULL,'end_date' => NULL,'cover_image' => NULL,'cover_image_url' => 'https://i.pinimg.com/564x/35/0f/0b/350f0bb9663bfbf656d4cbb070a2def2.jpg','uuid' => '7ZCMdI9yXqInPGVWn8e99Gnu','status' => '1','user_id' => '1','created_at' => '2025-02-27 14:43:28','updated_at' => '2025-02-27 14:43:28'),
        array('id' => '25','title' => 'Juego de Tronos','slug' => 'juego-de-tronos','synopsis' => 'Nueve familias nobles luchan por el control de las tierras de Poniente, mientras que un antiguo enemigo regresa después de estar inactivo durante milenios.','release_date' => '2011-01-01','number_collection' => NULL,'duration' => NULL,'rating' => '4','personal_description' => NULL,'media_type' => '2','start_date' => '2013-02-01','end_date' => '2020-01-01','cover_image' => NULL,'cover_image_url' => 'https://hips.hearstapps.com/hmg-prod/images/juego-de-tronos-primera-temporada-1558599291.jpg?resize=640:*','uuid' => 'CujuVCGNgpUiQrWFiO6YJL0i','status' => '2','user_id' => '1','created_at' => '2025-02-27 15:02:50','updated_at' => '2025-02-27 15:04:57'),
        array('id' => '26','title' => 'Ataque de Titanes','slug' => 'ataque-de-titanes','synopsis' => 'La historia está ambientada en la isla «Paradis», ubicada al noreste del país de «Marley», en donde Eren Jaeger vive con su familia; con su hermana adoptiva, Mikasa Ackerman; y con su mejor amigo, Armin Arlert. Su pueblo colinda con la «muralla María», la más externa del Reino de las «tres murallas». Estas enormes murallas fueron construidas cien años atrás, con el fin de protegerse de los «titanes», criaturas de entre tres y sesenta metros de alto que casi aniquilaron a la humanidad. Además de su gran tamaño, los titanes se caracterizan por su estructura corporal parecida a la de los humanos, a quienes devoran de forma instintiva, y la única manera conocida de matarlos es cortándoles la nuca. ','release_date' => '2013-01-01','number_collection' => NULL,'duration' => NULL,'rating' => '3','personal_description' => NULL,'media_type' => '2','start_date' => '2022-01-01','end_date' => '2025-01-13','cover_image' => NULL,'cover_image_url' => 'https://i1.whakoom.com/large/1d/2e/7b89b49c41c94c2ab9244524104c2afd.jpg','uuid' => 'FxPmt9RxTzoDxKimI7jkas1F','status' => '2','user_id' => '1','created_at' => '2025-02-27 15:13:59','updated_at' => '2025-02-28 19:31:59'),
        array('id' => '27','title' => 'El Juego del Calamar','slug' => 'el-juego-del-calamar','synopsis' => '456 participantes desesperados compiten en un misterioso y mortífero concurso de supervivencia compuesto de varias rondas de juegos infantiles. ¿La meta? Ganar 45.600 millones de wones y salir de la miseria.','release_date' => '2021-01-01','number_collection' => NULL,'duration' => NULL,'rating' => '4','personal_description' => NULL,'media_type' => '2','start_date' => '2021-01-01','end_date' => NULL,'cover_image' => NULL,'cover_image_url' => 'https://es.web.img3.acsta.net/pictures/21/09/29/12/02/1288399.jpg','uuid' => 's8GE9ilwUFDajgnq3Ixs0eqB','status' => '3','user_id' => '1','created_at' => '2025-02-27 15:27:27','updated_at' => '2025-02-27 15:27:27'),
        array('id' => '28','title' => 'Re Loca','slug' => 're-loca','synopsis' => 'Una mujer de unos 40 años se siente atrapada en una rutina en su carrera y su vida amorosa. Decide cambiar un poco las cosas, pero el ritual que intenta tiene consecuencias que pondrán su vida patas arriba.','release_date' => '2018-01-01','number_collection' => '1','duration' => '94','rating' => '4','personal_description' => '<p>Una peli muy común y familiar, pero tiene cositas que estuvieron muy buenas.</p><p>Más que nada trata de como te toman de boludo cuando más bueno sos, y a la protagonista le hacen creer que con un ritual puede cambiar el carácter, a partir de ahí empieza a decir y hacer todo lo que piensa.</p><p>Está bueno como reacciona la gente al ver cosas que no diría y demás, pero lo que más me quedo es ver cómo ella pudo cambiar y hacer cosas que quería y el chico que era el amor que siempre tuvo, se resigno a una vida triste por ser sumiso, lo maltrata la mujer y todos</p><p>Ella eligió estar sola pero bien, cuando el otro eligió ser sumiso con su mujer ideal.</p>','media_type' => '1','start_date' => NULL,'end_date' => '2025-02-14','cover_image' => NULL,'cover_image_url' => 'https://m.media-amazon.com/images/M/MV5BYTk2NjYxZWEtOGE4ZS00OTg4LWI4MTMtNDM3NzcyM2IyZDQ2XkEyXkFqcGc@._V1_.jpg','uuid' => '60bhrMaQ2xyzC3xQfTziaPYK','status' => '2','user_id' => '1','created_at' => '2025-02-28 16:10:50','updated_at' => '2025-02-28 19:30:03'),
        array('id' => '29','title' => 'Soul','slug' => 'soul','synopsis' => 'Tras conseguir el concierto de su vida, un pianista de jazz neoyorquino se encuentra de repente atrapado en un extraño lugar entre la Tierra y el más allá.','release_date' => '2020-01-01','number_collection' => NULL,'duration' => '100','rating' => NULL,'personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://pics.filmaffinity.com/Soul-827520959-large.jpg','uuid' => 'BluiL9wvWq1QwlWU8ckq82rr','status' => '2','user_id' => '1','created_at' => '2025-02-28 17:11:36','updated_at' => '2025-02-28 17:11:36'),
        array('id' => '30','title' => 'Los Increíbles','slug' => 'los-increibles','synopsis' => 'Mientras intenta llevar una tranquila vida suburbana, una familia de superhéroes encubiertos se ve obligada a entrar en acción para salvar el mundo.','release_date' => '2004-01-01','number_collection' => '1','duration' => '115','rating' => NULL,'personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img2.acsta.net/medias/nmedia/18/89/87/86/20070947.jpg','uuid' => 'Fhwvin9uq10decYu5Y3AnHlz','status' => '2','user_id' => '1','created_at' => '2025-02-28 17:14:30','updated_at' => '2025-02-28 17:14:30'),
        array('id' => '31','title' => 'Los Increíbles 2','slug' => 'los-increibles-2','synopsis' => 'Los Increíbles asumen una nueva misión que implica un cambio de roles familiares, Mr. Increíble se encargará de la casa mientras su esposa Elastigirl salva al mundo.','release_date' => '2018-01-01','number_collection' => '2','duration' => '118','rating' => NULL,'personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://es.web.img3.acsta.net/pictures/18/04/13/11/46/5802807.jpg','uuid' => 'jxpkdKq8HkunkXyPtGejo1mH','status' => '2','user_id' => '1','created_at' => '2025-02-28 17:15:51','updated_at' => '2025-02-28 17:15:51'),
        array('id' => '32','title' => 'Monstruos University','slug' => 'monstruos-university','synopsis' => 'Una mirada a la relación entre Mike Wazowski y James P. Sullivan durante sus días en Monstruos University, cuando no eran precisamente los mejores amigos.','release_date' => '2013-01-01','number_collection' => '2','duration' => '104','rating' => NULL,'personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => NULL,'cover_image' => NULL,'cover_image_url' => 'https://i.pinimg.com/736x/bd/1d/be/bd1dbecd4790b4d7ab6c64837b3f6407.jpg','uuid' => '8e28S3hJaEN0WmA426Xxh1Sn','status' => '1','user_id' => '1','created_at' => '2025-02-28 17:17:38','updated_at' => '2025-02-28 17:17:38'),
        array('id' => '33','title' => 'Monsters, Inc.','slug' => 'monsters-inc','synopsis' => 'Para darle energía a la ciudad, los monstruos tienen que asustar a los niños para que griten. Sin embargo, los niños son tóxicos para los monstruos, y después de que un niño supera, dos monstruos se dan cuenta de que las cosas pueden no ser lo que piensan.','release_date' => '2001-01-01','number_collection' => '1','duration' => '92','rating' => NULL,'personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR79FEy20MOxKz_2Vj4HI6tMi1qxGS-vAT9Lg&s','uuid' => 'cUFad2KccH8xQnQSv1sWtgEo','status' => '2','user_id' => '1','created_at' => '2025-02-28 17:19:34','updated_at' => '2025-02-28 17:31:56'),
        array('id' => '34','title' => 'Ratatouille','slug' => 'ratatouille','synopsis' => 'Una rata que sabe cocinar establece una inusual alianza con un joven trabajador de la cocina de un famoso restaurante de París.','release_date' => '2007-01-01','number_collection' => '1','duration' => '111','rating' => NULL,'personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://pics.filmaffinity.com/Ratatouille-828434562-large.jpg','uuid' => 'mi6JG41WlcZfzXmMC7SIdSV4','status' => '2','user_id' => '1','created_at' => '2025-02-28 17:34:55','updated_at' => '2025-02-28 17:34:55'),
        array('id' => '35','title' => 'Up','slug' => 'up','synopsis' => 'Carl Fredricksen, de 78 años, viaja a las cataratas Paraíso en su casa equipada con globos, sin darse cuenta de que lleva a un polizón.','release_date' => '2009-01-01','number_collection' => '1','duration' => '96','rating' => NULL,'personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2024-01-01','cover_image' => NULL,'cover_image_url' => 'https://www.funeralnatural.net/sites/default/files/pelicula/imagen/upcartel.jpg','uuid' => '0TlKi07oGu2yQDO1APbQDgro','status' => '2','user_id' => '1','created_at' => '2025-02-28 17:44:50','updated_at' => '2025-02-28 17:44:50'),
        array('id' => '36','title' => 'The Wild Robot','slug' => 'the-wild-robot','synopsis' => 'Un robot llamado Roz naufraga en una isla, donde debe aprender a adaptarse a su nuevo entorno, al establecer relaciones con los animales del lugar, pronto desarrolla un vínculo paternal con un ganso huérfano.','release_date' => '2024-01-01','number_collection' => '1','duration' => '104','rating' => '4','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => '2025-02-06','cover_image' => NULL,'cover_image_url' => 'https://pics.filmaffinity.com/Robot_salvaje-888634955-large.jpg','uuid' => 'GIstkU1inW0ybc6bmRixQX4S','status' => '2','user_id' => '1','created_at' => '2025-03-07 11:38:55','updated_at' => '2025-03-08 02:52:36'),
        array('id' => '37','title' => 'One Piece','slug' => 'one-piece','synopsis' => NULL,'release_date' => '1999-01-01','number_collection' => '1','duration' => NULL,'rating' => '5','personal_description' => NULL,'media_type' => '2','start_date' => '2024-01-01','end_date' => NULL,'cover_image' => NULL,'cover_image_url' => 'https://pics.filmaffinity.com/one_piece-647985949-mmed.jpg','uuid' => 'iDAkMJyiWgE0BSVp8dCGTkhL','status' => '3','user_id' => '1','created_at' => '2025-03-07 12:37:44','updated_at' => '2025-03-08 03:31:52'),
        array('id' => '38','title' => 'asd','slug' => 'asd','synopsis' => NULL,'release_date' => NULL,'number_collection' => '1','duration' => NULL,'rating' => '0','personal_description' => NULL,'media_type' => '1','start_date' => NULL,'end_date' => NULL,'cover_image' => NULL,'cover_image_url' => NULL,'uuid' => 'C0QkpK4NFbkUGFNPKKbbOLTi','status' => '1','user_id' => '1','created_at' => '2025-03-09 12:06:32','updated_at' => '2025-03-09 12:06:32')
      );

    public function run(): void
    {
        foreach($this->media as $item){
            Media::create($item);
        }
    }
}
